name: phys570
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterhub
  - pydot
  - graphviz
  - pip
  - pip:
    - jupyter
    - tensorflow==2.4.0
    - tensorflow_datasets
    - qkeras==0.9.0
    - scikit-learn
    - conifer==0.2b0
    - hls4ml==0.6.0
    - pytz==2022.5
    - kaggle==1.5.12
    - opendatasets==0.1.22
    - tensorflow-gpu==2.10.0

